baseurl = "https://pushpdeep.github.io/testhugo/"
languageCode = "en-us"
title = "Pushpdeep-Hugo-Site"
newContentEditor = "nano"
theme = "aerial"
publishDir = "docs"
pygmentsStyle = "native"


[params]
  name = "Pushpdeep Mishra"
  about = "Project Manager &nbsp;&bull;&nbsp; Cyborg &nbsp;&bull;&nbsp; Never asked for this"
  copyright = "2019-IIT Bombay"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://www.twitter.com/pushpdeep"

[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "https://www.facebook.com/pushpdeep.mishra"

[[params.social]]
  medium = "Dribbble"
  icon = "dribbble"
  link = "#"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://www.github.com/pushpdeep"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "pushpdeep@iitb.ac.in"
